### ISSUE TITLE
Signature one byte off

### ISSUE THREAD

**Issue by evilteq** [canonical/aws-secureboot-blob#7]
https://github.com/canonical/aws-secureboot-blob/blob/7673cf023fbff0b322025a17cf84a06b18e2855b/dbxupdate-split.py#L44

The signature is missing one byte, the - 1 in the array "to" is wrong.

**Comment by toabctl** [comment]
@evilteq thx for reporting. How do you know that it's one byte off? Can you elaborate on that a bit please?

**Comment by evilteq** [comment]
The slicing goes from 0 up to (and not including) the (signature_length - 1)'th byte. The resulting array is signature_length - 1 bytes, and not signature_length.

**Comment by evilteq** [comment]
Shall I provide a fix?

**Comment by toabctl** [comment]
> Shall I provide a fix?

sure (and sorry for the late response)

**Comment by evilteq** [comment]
That commit will fix it.
